name: once
description: Want to run a piece of code once periodically (Once - Daily - Weekly - Monthly - On new build - On new version - Any period)? We cover your back.
version: 1.5.4
homepage: https://github.com/MostafaSolimanMO/once

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.3

topic:
  - utils
  - storage
  - persistence